"""add summary fields to llms_files

Revision ID: 36115fb36911
Revises: faac4995d7b3
Create Date: 2026-04-12 17:45:00.314182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36115fb36911'
down_revision: Union[str, Sequence[str], None] = 'faac4995d7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms_files', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('llms_files', sa.Column('summary_generated', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llms_files', 'summary_generated')
    op.drop_column('llms_files', 'summary')
    # ### end Alembic commands ###
