"""add_slug_to_sites

Revision ID: b4b4235162ba
Revises: 36115fb36911
Create Date: 2026-04-13 18:20:07.405217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b4235162ba'
down_revision: Union[str, Sequence[str], None] = '36115fb36911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_sites_slug'), 'sites', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_slug'), table_name='sites')
    op.drop_column('sites', 'slug')
    # ### end Alembic commands ###
